/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


/**
 *
 * @author Japa
 */
public final class Telasabermais extends javax.swing.JFrame {

    /**
     * Creates new form Telasabermais
     */
    public Telasabermais() {
        initComponents();
        transparenciaBotao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btjogar = new javax.swing.JButton();
        Btvoltar = new javax.swing.JButton();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(820, 630));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        Btjogar.setBackground(new java.awt.Color(0, 0, 0));
        Btjogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Botão Jogar 2.png"))); // NOI18N
        Btjogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtjogarActionPerformed(evt);
            }
        });
        getContentPane().add(Btjogar);
        Btjogar.setBounds(410, 510, 150, 80);

        Btvoltar.setBackground(new java.awt.Color(0, 0, 0));
        Btvoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Voltar.png"))); // NOI18N
        Btvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtvoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Btvoltar);
        Btvoltar.setBounds(250, 510, 150, 80);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Fundo Saber Mais.png"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, -20, 800, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        public void transparenciaBotao(){

Btjogar.setOpaque(false);
Btjogar.setContentAreaFilled(false);
Btjogar.setBorderPainted(false);
Btvoltar.setOpaque(false);
Btvoltar.setContentAreaFilled(false);
Btvoltar.setBorderPainted(false);


}
        
    private void BtjogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtjogarActionPerformed
        // TODO add your handling code here:
         new TelaInicial().setVisible(true);

         dispose();
                
    }//GEN-LAST:event_BtjogarActionPerformed

    private void BtvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtvoltarActionPerformed
        // TODO add your handling code here:
        new TelaPrincipal().setVisible(true);

        dispose();
        
    }//GEN-LAST:event_BtvoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telasabermais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telasabermais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telasabermais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telasabermais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telasabermais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btjogar;
    private javax.swing.JButton Btvoltar;
    private javax.swing.JLabel Fundo;
    // End of variables declaration//GEN-END:variables
}
